name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: artifacts/hello.txt   # Adjusted path to include "artifacts" folder

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create artifacts directory
        run: mkdir -p ./artifacts   # Create the "artifacts" directory if it doesn't exist

      - name: download text file
        uses: actions/download-artifact@v2
        with:
          name: hello-artifact
          path: ./artifacts

      - name: echo
        run : cat ./artifacts/hello.txt
